# golangci-lint v2 configuration
version: "2"

linters:
  # Use default enabled linters plus a few extras
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - revive

  # Linter-specific settings (moved from linters-settings in v1)
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    json:
      path: stdout
