# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  # Skip tools build tag to avoid HCL v2.24.0 tools.go import issue

linters:
  # Enable default linters plus additional useful ones
  enable:
    - errcheck      # Check for unchecked errors (default)
    - govet         # Vet examines Go source code (default)
    - ineffassign   # Detect ineffectual assignments (default)
    - staticcheck   # Static analysis (default)
    - unused        # Check for unused code (default)
    - bodyclose     # Check HTTP response body is closed
    - errorlint     # Check error wrapping
    - gocritic      # Meta linter with various checks
    - gosec         # Security checker
    - misspell      # Check for misspellings
    - revive        # Fast, configurable, extensible linter

# Note: gosimple and exportloopref removed in v2 (functionality in staticcheck)
# Note: gofmt and goimports are formatters in v2, not linters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  revive:
    confidence: 0.8
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude linters from test files
    - path: _test\.go
      linters:
        - gosec        # Security checks less critical in tests
        - errcheck     # Unchecked errors acceptable in tests
        - gocritic     # Style checks less critical in tests
        - revive       # Documentation requirements relaxed in tests
        - bodyclose    # HTTP body close checks relaxed in tests
        - errorlint    # Error wrapping less critical in tests

    # Allow unused ctx parameters (common in Terraform providers)
    - text: "unused-parameter.*ctx"
      linters:
        - revive

    # Allow missing comments on exported provider methods (framework requirement)
    - path: internal/provider/
      text: "exported.*should have comment"
      linters:
        - revive

    # Allow missing package comments
    - text: "package-comments"
      linters:
        - revive

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
