# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

# Generate SBOM (Software Bill of Materials) for supply chain security
sboms:
  - artifacts: binary
    cmd: syft
    args: ["$artifact", "--output", "spdx-json=$document"]
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.spdx.json"

release:
  github:
    owner: braintrustdata
    name: terraform-provider-braintrustdata
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Terraform Provider for Braintrust {{ .Version }}

    This release includes updates to the Braintrust Terraform provider.

    ### Installation

    Add the following to your Terraform configuration:

    ```terraform
    terraform {
      required_providers {
        braintrustdata = {
          source  = "braintrustdata/braintrustdata"
          version = "{{ .Version }}"
        }
      }
    }
    ```

    ### Changes

    See CHANGELOG.md for detailed changes.

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'README'
      - Merge pull request
      - Merge remote-tracking branch
